// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/controller"
	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolveTransformerMux creates a new instance of MockResolveTransformerMux. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolveTransformerMux(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolveTransformerMux {
	mock := &MockResolveTransformerMux{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolveTransformerMux is an autogenerated mock type for the ResolveTransformerMux type
type MockResolveTransformerMux struct {
	mock.Mock
}

type MockResolveTransformerMux_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolveTransformerMux) EXPECT() *MockResolveTransformerMux_Expecter {
	return &MockResolveTransformerMux_Expecter{mock: &_m.Mock}
}

// ResolveAndTransform provides a mock function for the type MockResolveTransformerMux
func (_mock *MockResolveTransformerMux) ResolveAndTransform(ctx context.Context, content types.Content, selectors types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, content, selectors)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAndTransform")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, content, selectors)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, content, selectors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Content, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, content, selectors)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolveTransformerMux_ResolveAndTransform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAndTransform'
type MockResolveTransformerMux_ResolveAndTransform_Call struct {
	*mock.Call
}

// ResolveAndTransform is a helper method to define mock.On call
//   - ctx context.Context
//   - content types.Content
//   - selectors types.IPXESelectors
func (_e *MockResolveTransformerMux_Expecter) ResolveAndTransform(ctx interface{}, content interface{}, selectors interface{}) *MockResolveTransformerMux_ResolveAndTransform_Call {
	return &MockResolveTransformerMux_ResolveAndTransform_Call{Call: _e.mock.On("ResolveAndTransform", ctx, content, selectors)}
}

func (_c *MockResolveTransformerMux_ResolveAndTransform_Call) Run(run func(ctx context.Context, content types.Content, selectors types.IPXESelectors)) *MockResolveTransformerMux_ResolveAndTransform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Content
		if args[1] != nil {
			arg1 = args[1].(types.Content)
		}
		var arg2 types.IPXESelectors
		if args[2] != nil {
			arg2 = args[2].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResolveTransformerMux_ResolveAndTransform_Call) Return(bytes []byte, err error) *MockResolveTransformerMux_ResolveAndTransform_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockResolveTransformerMux_ResolveAndTransform_Call) RunAndReturn(run func(ctx context.Context, content types.Content, selectors types.IPXESelectors) ([]byte, error)) *MockResolveTransformerMux_ResolveAndTransform_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAndTransformBatch provides a mock function for the type MockResolveTransformerMux
func (_mock *MockResolveTransformerMux) ResolveAndTransformBatch(ctx context.Context, batch map[string]types.Content, selectors types.IPXESelectors, options ...controller.ResolveTransformBatchOption) (map[string][]byte, error) {
	// controller.ResolveTransformBatchOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, batch, selectors)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAndTransformBatch")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]types.Content, types.IPXESelectors, ...controller.ResolveTransformBatchOption) (map[string][]byte, error)); ok {
		return returnFunc(ctx, batch, selectors, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]types.Content, types.IPXESelectors, ...controller.ResolveTransformBatchOption) map[string][]byte); ok {
		r0 = returnFunc(ctx, batch, selectors, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]types.Content, types.IPXESelectors, ...controller.ResolveTransformBatchOption) error); ok {
		r1 = returnFunc(ctx, batch, selectors, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolveTransformerMux_ResolveAndTransformBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAndTransformBatch'
type MockResolveTransformerMux_ResolveAndTransformBatch_Call struct {
	*mock.Call
}

// ResolveAndTransformBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch map[string]types.Content
//   - selectors types.IPXESelectors
//   - options ...controller.ResolveTransformBatchOption
func (_e *MockResolveTransformerMux_Expecter) ResolveAndTransformBatch(ctx interface{}, batch interface{}, selectors interface{}, options ...interface{}) *MockResolveTransformerMux_ResolveAndTransformBatch_Call {
	return &MockResolveTransformerMux_ResolveAndTransformBatch_Call{Call: _e.mock.On("ResolveAndTransformBatch",
		append([]interface{}{ctx, batch, selectors}, options...)...)}
}

func (_c *MockResolveTransformerMux_ResolveAndTransformBatch_Call) Run(run func(ctx context.Context, batch map[string]types.Content, selectors types.IPXESelectors, options ...controller.ResolveTransformBatchOption)) *MockResolveTransformerMux_ResolveAndTransformBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]types.Content
		if args[1] != nil {
			arg1 = args[1].(map[string]types.Content)
		}
		var arg2 types.IPXESelectors
		if args[2] != nil {
			arg2 = args[2].(types.IPXESelectors)
		}
		var arg3 []controller.ResolveTransformBatchOption
		variadicArgs := make([]controller.ResolveTransformBatchOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(controller.ResolveTransformBatchOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockResolveTransformerMux_ResolveAndTransformBatch_Call) Return(stringToBytes map[string][]byte, err error) *MockResolveTransformerMux_ResolveAndTransformBatch_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockResolveTransformerMux_ResolveAndTransformBatch_Call) RunAndReturn(run func(ctx context.Context, batch map[string]types.Content, selectors types.IPXESelectors, options ...controller.ResolveTransformBatchOption) (map[string][]byte, error)) *MockResolveTransformerMux_ResolveAndTransformBatch_Call {
	_c.Call.Return(run)
	return _c
}
