// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPXE creates a new instance of MockIPXE. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPXE(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPXE {
	mock := &MockIPXE{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPXE is an autogenerated mock type for the IPXE type
type MockIPXE struct {
	mock.Mock
}

type MockIPXE_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPXE) EXPECT() *MockIPXE_Expecter {
	return &MockIPXE_Expecter{mock: &_m.Mock}
}

// Boostrap provides a mock function for the type MockIPXE
func (_mock *MockIPXE) Boostrap() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Boostrap")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockIPXE_Boostrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boostrap'
type MockIPXE_Boostrap_Call struct {
	*mock.Call
}

// Boostrap is a helper method to define mock.On call
func (_e *MockIPXE_Expecter) Boostrap() *MockIPXE_Boostrap_Call {
	return &MockIPXE_Boostrap_Call{Call: _e.mock.On("Boostrap")}
}

func (_c *MockIPXE_Boostrap_Call) Run(run func()) *MockIPXE_Boostrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPXE_Boostrap_Call) Return(bytes []byte) *MockIPXE_Boostrap_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockIPXE_Boostrap_Call) RunAndReturn(run func() []byte) *MockIPXE_Boostrap_Call {
	_c.Call.Return(run)
	return _c
}

// FindProfileAndRender provides a mock function for the type MockIPXE
func (_mock *MockIPXE) FindProfileAndRender(ctx context.Context, selectors types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, selectors)

	if len(ret) == 0 {
		panic("no return value specified for FindProfileAndRender")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, selectors)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, selectors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, selectors)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPXE_FindProfileAndRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProfileAndRender'
type MockIPXE_FindProfileAndRender_Call struct {
	*mock.Call
}

// FindProfileAndRender is a helper method to define mock.On call
//   - ctx context.Context
//   - selectors types.IPXESelectors
func (_e *MockIPXE_Expecter) FindProfileAndRender(ctx interface{}, selectors interface{}) *MockIPXE_FindProfileAndRender_Call {
	return &MockIPXE_FindProfileAndRender_Call{Call: _e.mock.On("FindProfileAndRender", ctx, selectors)}
}

func (_c *MockIPXE_FindProfileAndRender_Call) Run(run func(ctx context.Context, selectors types.IPXESelectors)) *MockIPXE_FindProfileAndRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.IPXESelectors
		if args[1] != nil {
			arg1 = args[1].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPXE_FindProfileAndRender_Call) Return(bytes []byte, err error) *MockIPXE_FindProfileAndRender_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIPXE_FindProfileAndRender_Call) RunAndReturn(run func(ctx context.Context, selectors types.IPXESelectors) ([]byte, error)) *MockIPXE_FindProfileAndRender_Call {
	_c.Call.Return(run)
	return _c
}
