// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContent creates a new instance of MockContent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContent {
	mock := &MockContent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContent is an autogenerated mock type for the Content type
type MockContent struct {
	mock.Mock
}

type MockContent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContent) EXPECT() *MockContent_Expecter {
	return &MockContent_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockContent
func (_mock *MockContent) GetByID(ctx context.Context, contentID uuid.UUID, attributes types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, contentID, attributes)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, contentID, attributes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, contentID, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, contentID, attributes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContent_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockContent_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - contentID uuid.UUID
//   - attributes types.IPXESelectors
func (_e *MockContent_Expecter) GetByID(ctx interface{}, contentID interface{}, attributes interface{}) *MockContent_GetByID_Call {
	return &MockContent_GetByID_Call{Call: _e.mock.On("GetByID", ctx, contentID, attributes)}
}

func (_c *MockContent_GetByID_Call) Run(run func(ctx context.Context, contentID uuid.UUID, attributes types.IPXESelectors)) *MockContent_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 types.IPXESelectors
		if args[2] != nil {
			arg2 = args[2].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContent_GetByID_Call) Return(bytes []byte, err error) *MockContent_GetByID_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockContent_GetByID_Call) RunAndReturn(run func(ctx context.Context, contentID uuid.UUID, attributes types.IPXESelectors) ([]byte, error)) *MockContent_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
