/*
Copyright 2024 Alexandre Mahdhaoui

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockadapter

import (
	context "context"

	types "github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, content, attributes
func (_m *MockResolver) Resolve(ctx context.Context, content types.Content, attributes types.IPXESelectors) ([]byte, error) {
	ret := _m.Called(ctx, content, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) ([]byte, error)); ok {
		return rf(ctx, content, attributes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) []byte); ok {
		r0 = rf(ctx, content, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.Content, types.IPXESelectors) error); ok {
		r1 = rf(ctx, content, attributes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - content types.Content
//   - attributes types.IPXESelectors
func (_e *MockResolver_Expecter) Resolve(ctx interface{}, content interface{}, attributes interface{}) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, content, attributes)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(ctx context.Context, content types.Content, attributes types.IPXESelectors)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.Content), args[2].(types.IPXESelectors))
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(_a0 []byte, _a1 error) *MockResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(context.Context, types.Content, types.IPXESelectors) ([]byte, error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
