// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransformer creates a new instance of MockTransformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransformer {
	mock := &MockTransformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransformer is an autogenerated mock type for the Transformer type
type MockTransformer struct {
	mock.Mock
}

type MockTransformer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransformer) EXPECT() *MockTransformer_Expecter {
	return &MockTransformer_Expecter{mock: &_m.Mock}
}

// Transform provides a mock function for the type MockTransformer
func (_mock *MockTransformer) Transform(ctx context.Context, cfg types.TransformerConfig, content []byte, selectors types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, cfg, content, selectors)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, cfg, content, selectors)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, cfg, content, selectors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, cfg, content, selectors)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransformer_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type MockTransformer_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg types.TransformerConfig
//   - content []byte
//   - selectors types.IPXESelectors
func (_e *MockTransformer_Expecter) Transform(ctx interface{}, cfg interface{}, content interface{}, selectors interface{}) *MockTransformer_Transform_Call {
	return &MockTransformer_Transform_Call{Call: _e.mock.On("Transform", ctx, cfg, content, selectors)}
}

func (_c *MockTransformer_Transform_Call) Run(run func(ctx context.Context, cfg types.TransformerConfig, content []byte, selectors types.IPXESelectors)) *MockTransformer_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.TransformerConfig
		if args[1] != nil {
			arg1 = args[1].(types.TransformerConfig)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 types.IPXESelectors
		if args[3] != nil {
			arg3 = args[3].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransformer_Transform_Call) Return(bytes []byte, err error) *MockTransformer_Transform_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTransformer_Transform_Call) RunAndReturn(run func(ctx context.Context, cfg types.TransformerConfig, content []byte, selectors types.IPXESelectors) ([]byte, error)) *MockTransformer_Transform_Call {
	_c.Call.Return(run)
	return _c
}
