// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssignment creates a new instance of MockAssignment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssignment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssignment {
	mock := &MockAssignment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssignment is an autogenerated mock type for the Assignment type
type MockAssignment struct {
	mock.Mock
}

type MockAssignment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssignment) EXPECT() *MockAssignment_Expecter {
	return &MockAssignment_Expecter{mock: &_m.Mock}
}

// FindBySelectors provides a mock function for the type MockAssignment
func (_mock *MockAssignment) FindBySelectors(ctx context.Context, selectors types.IPXESelectors) (types.Assignment, error) {
	ret := _mock.Called(ctx, selectors)

	if len(ret) == 0 {
		panic("no return value specified for FindBySelectors")
	}

	var r0 types.Assignment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.IPXESelectors) (types.Assignment, error)); ok {
		return returnFunc(ctx, selectors)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.IPXESelectors) types.Assignment); ok {
		r0 = returnFunc(ctx, selectors)
	} else {
		r0 = ret.Get(0).(types.Assignment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, selectors)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssignment_FindBySelectors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySelectors'
type MockAssignment_FindBySelectors_Call struct {
	*mock.Call
}

// FindBySelectors is a helper method to define mock.On call
//   - ctx context.Context
//   - selectors types.IPXESelectors
func (_e *MockAssignment_Expecter) FindBySelectors(ctx interface{}, selectors interface{}) *MockAssignment_FindBySelectors_Call {
	return &MockAssignment_FindBySelectors_Call{Call: _e.mock.On("FindBySelectors", ctx, selectors)}
}

func (_c *MockAssignment_FindBySelectors_Call) Run(run func(ctx context.Context, selectors types.IPXESelectors)) *MockAssignment_FindBySelectors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.IPXESelectors
		if args[1] != nil {
			arg1 = args[1].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssignment_FindBySelectors_Call) Return(assignment types.Assignment, err error) *MockAssignment_FindBySelectors_Call {
	_c.Call.Return(assignment, err)
	return _c
}

func (_c *MockAssignment_FindBySelectors_Call) RunAndReturn(run func(ctx context.Context, selectors types.IPXESelectors) (types.Assignment, error)) *MockAssignment_FindBySelectors_Call {
	_c.Call.Return(run)
	return _c
}

// FindDefaultByBuildarch provides a mock function for the type MockAssignment
func (_mock *MockAssignment) FindDefaultByBuildarch(ctx context.Context, buildarch string) (types.Assignment, error) {
	ret := _mock.Called(ctx, buildarch)

	if len(ret) == 0 {
		panic("no return value specified for FindDefaultByBuildarch")
	}

	var r0 types.Assignment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Assignment, error)); ok {
		return returnFunc(ctx, buildarch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Assignment); ok {
		r0 = returnFunc(ctx, buildarch)
	} else {
		r0 = ret.Get(0).(types.Assignment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, buildarch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssignment_FindDefaultByBuildarch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDefaultByBuildarch'
type MockAssignment_FindDefaultByBuildarch_Call struct {
	*mock.Call
}

// FindDefaultByBuildarch is a helper method to define mock.On call
//   - ctx context.Context
//   - buildarch string
func (_e *MockAssignment_Expecter) FindDefaultByBuildarch(ctx interface{}, buildarch interface{}) *MockAssignment_FindDefaultByBuildarch_Call {
	return &MockAssignment_FindDefaultByBuildarch_Call{Call: _e.mock.On("FindDefaultByBuildarch", ctx, buildarch)}
}

func (_c *MockAssignment_FindDefaultByBuildarch_Call) Run(run func(ctx context.Context, buildarch string)) *MockAssignment_FindDefaultByBuildarch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssignment_FindDefaultByBuildarch_Call) Return(assignment types.Assignment, err error) *MockAssignment_FindDefaultByBuildarch_Call {
	_c.Call.Return(assignment, err)
	return _c
}

func (_c *MockAssignment_FindDefaultByBuildarch_Call) RunAndReturn(run func(ctx context.Context, buildarch string) (types.Assignment, error)) *MockAssignment_FindDefaultByBuildarch_Call {
	_c.Call.Return(run)
	return _c
}
