// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/util/jsonpath"
)

// NewMockObjectRefResolver creates a new instance of MockObjectRefResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectRefResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectRefResolver {
	mock := &MockObjectRefResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectRefResolver is an autogenerated mock type for the ObjectRefResolver type
type MockObjectRefResolver struct {
	mock.Mock
}

type MockObjectRefResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectRefResolver) EXPECT() *MockObjectRefResolver_Expecter {
	return &MockObjectRefResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockObjectRefResolver
func (_mock *MockObjectRefResolver) Resolve(ctx context.Context, content types.Content, attributes types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, content, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, content, attributes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, content, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Content, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, content, attributes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectRefResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockObjectRefResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - content types.Content
//   - attributes types.IPXESelectors
func (_e *MockObjectRefResolver_Expecter) Resolve(ctx interface{}, content interface{}, attributes interface{}) *MockObjectRefResolver_Resolve_Call {
	return &MockObjectRefResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, content, attributes)}
}

func (_c *MockObjectRefResolver_Resolve_Call) Run(run func(ctx context.Context, content types.Content, attributes types.IPXESelectors)) *MockObjectRefResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Content
		if args[1] != nil {
			arg1 = args[1].(types.Content)
		}
		var arg2 types.IPXESelectors
		if args[2] != nil {
			arg2 = args[2].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectRefResolver_Resolve_Call) Return(bytes []byte, err error) *MockObjectRefResolver_Resolve_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockObjectRefResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, content types.Content, attributes types.IPXESelectors) ([]byte, error)) *MockObjectRefResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePaths provides a mock function for the type MockObjectRefResolver
func (_mock *MockObjectRefResolver) ResolvePaths(ctx context.Context, paths []*jsonpath.JSONPath, ref types.ObjectRef) ([][]byte, error) {
	ret := _mock.Called(ctx, paths, ref)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePaths")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*jsonpath.JSONPath, types.ObjectRef) ([][]byte, error)); ok {
		return returnFunc(ctx, paths, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*jsonpath.JSONPath, types.ObjectRef) [][]byte); ok {
		r0 = returnFunc(ctx, paths, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*jsonpath.JSONPath, types.ObjectRef) error); ok {
		r1 = returnFunc(ctx, paths, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectRefResolver_ResolvePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePaths'
type MockObjectRefResolver_ResolvePaths_Call struct {
	*mock.Call
}

// ResolvePaths is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []*jsonpath.JSONPath
//   - ref types.ObjectRef
func (_e *MockObjectRefResolver_Expecter) ResolvePaths(ctx interface{}, paths interface{}, ref interface{}) *MockObjectRefResolver_ResolvePaths_Call {
	return &MockObjectRefResolver_ResolvePaths_Call{Call: _e.mock.On("ResolvePaths", ctx, paths, ref)}
}

func (_c *MockObjectRefResolver_ResolvePaths_Call) Run(run func(ctx context.Context, paths []*jsonpath.JSONPath, ref types.ObjectRef)) *MockObjectRefResolver_ResolvePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*jsonpath.JSONPath
		if args[1] != nil {
			arg1 = args[1].([]*jsonpath.JSONPath)
		}
		var arg2 types.ObjectRef
		if args[2] != nil {
			arg2 = args[2].(types.ObjectRef)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectRefResolver_ResolvePaths_Call) Return(bytess [][]byte, err error) *MockObjectRefResolver_ResolvePaths_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockObjectRefResolver_ResolvePaths_Call) RunAndReturn(run func(ctx context.Context, paths []*jsonpath.JSONPath, ref types.ObjectRef) ([][]byte, error)) *MockObjectRefResolver_ResolvePaths_Call {
	_c.Call.Return(run)
	return _c
}
