// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(ctx context.Context, content types.Content, attributes types.IPXESelectors) ([]byte, error) {
	ret := _mock.Called(ctx, content, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) ([]byte, error)); ok {
		return returnFunc(ctx, content, attributes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.Content, types.IPXESelectors) []byte); ok {
		r0 = returnFunc(ctx, content, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.Content, types.IPXESelectors) error); ok {
		r1 = returnFunc(ctx, content, attributes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - content types.Content
//   - attributes types.IPXESelectors
func (_e *MockResolver_Expecter) Resolve(ctx interface{}, content interface{}, attributes interface{}) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, content, attributes)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(ctx context.Context, content types.Content, attributes types.IPXESelectors)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.Content
		if args[1] != nil {
			arg1 = args[1].(types.Content)
		}
		var arg2 types.IPXESelectors
		if args[2] != nil {
			arg2 = args[2].(types.IPXESelectors)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(bytes []byte, err error) *MockResolver_Resolve_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, content types.Content, attributes types.IPXESelectors) ([]byte, error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
