// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/shaper/internal/types"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfile creates a new instance of MockProfile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfile {
	mock := &MockProfile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfile is an autogenerated mock type for the Profile type
type MockProfile struct {
	mock.Mock
}

type MockProfile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfile) EXPECT() *MockProfile_Expecter {
	return &MockProfile_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockProfile
func (_mock *MockProfile) Get(ctx context.Context, name string) (types.Profile, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Profile, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Profile); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(types.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfile_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProfile_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockProfile_Expecter) Get(ctx interface{}, name interface{}) *MockProfile_Get_Call {
	return &MockProfile_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockProfile_Get_Call) Run(run func(ctx context.Context, name string)) *MockProfile_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfile_Get_Call) Return(profile types.Profile, err error) *MockProfile_Get_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfile_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (types.Profile, error)) *MockProfile_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByContentID provides a mock function for the type MockProfile
func (_mock *MockProfile) ListByContentID(ctx context.Context, configID uuid.UUID) ([]types.Profile, error) {
	ret := _mock.Called(ctx, configID)

	if len(ret) == 0 {
		panic("no return value specified for ListByContentID")
	}

	var r0 []types.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]types.Profile, error)); ok {
		return returnFunc(ctx, configID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []types.Profile); ok {
		r0 = returnFunc(ctx, configID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, configID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfile_ListByContentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByContentID'
type MockProfile_ListByContentID_Call struct {
	*mock.Call
}

// ListByContentID is a helper method to define mock.On call
//   - ctx context.Context
//   - configID uuid.UUID
func (_e *MockProfile_Expecter) ListByContentID(ctx interface{}, configID interface{}) *MockProfile_ListByContentID_Call {
	return &MockProfile_ListByContentID_Call{Call: _e.mock.On("ListByContentID", ctx, configID)}
}

func (_c *MockProfile_ListByContentID_Call) Run(run func(ctx context.Context, configID uuid.UUID)) *MockProfile_ListByContentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfile_ListByContentID_Call) Return(profiles []types.Profile, err error) *MockProfile_ListByContentID_Call {
	_c.Call.Return(profiles, err)
	return _c
}

func (_c *MockProfile_ListByContentID_Call) RunAndReturn(run func(ctx context.Context, configID uuid.UUID) ([]types.Profile, error)) *MockProfile_ListByContentID_Call {
	_c.Call.Return(run)
	return _c
}
