/*
Copyright 2024 Alexandre Mahdhaoui

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.42.0. DO NOT EDIT.

package mockadapter

import (
	context "context"

	types "github.com/alexandremahdhaoui/shaper/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// MockTransformer is an autogenerated mock type for the Transformer type
type MockTransformer struct {
	mock.Mock
}

type MockTransformer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransformer) EXPECT() *MockTransformer_Expecter {
	return &MockTransformer_Expecter{mock: &_m.Mock}
}

// Transform provides a mock function with given fields: ctx, cfg, content, selectors
func (_m *MockTransformer) Transform(ctx context.Context, cfg types.TransformerConfig, content []byte, selectors types.IPXESelectors) ([]byte, error) {
	ret := _m.Called(ctx, cfg, content, selectors)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) ([]byte, error)); ok {
		return rf(ctx, cfg, content, selectors)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) []byte); ok {
		r0 = rf(ctx, cfg, content, selectors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) error); ok {
		r1 = rf(ctx, cfg, content, selectors)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransformer_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type MockTransformer_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg types.TransformerConfig
//   - content []byte
//   - selectors types.IPXESelectors
func (_e *MockTransformer_Expecter) Transform(ctx interface{}, cfg interface{}, content interface{}, selectors interface{}) *MockTransformer_Transform_Call {
	return &MockTransformer_Transform_Call{Call: _e.mock.On("Transform", ctx, cfg, content, selectors)}
}

func (_c *MockTransformer_Transform_Call) Run(run func(ctx context.Context, cfg types.TransformerConfig, content []byte, selectors types.IPXESelectors)) *MockTransformer_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.TransformerConfig), args[2].([]byte), args[3].(types.IPXESelectors))
	})
	return _c
}

func (_c *MockTransformer_Transform_Call) Return(_a0 []byte, _a1 error) *MockTransformer_Transform_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransformer_Transform_Call) RunAndReturn(run func(context.Context, types.TransformerConfig, []byte, types.IPXESelectors) ([]byte, error)) *MockTransformer_Transform_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransformer creates a new instance of MockTransformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransformer {
	mock := &MockTransformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
