# Copyright 2024 Alexandre Mahdhaoui
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM docker.io/golang:1.25 AS downloader

WORKDIR /workdir

COPY ./go.* ./

RUN go mod download

FROM downloader AS builder

ARG GO_BUILD_LDFLAGS

ARG NAME=shaper-webhook
ARG INPUT_CMD="./cmd/${NAME}"
ARG OUTPUT_BIN="/bin/${NAME}"

WORKDIR /workdir

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \
    go build \
      -ldflags "-s -w -extldflags=-static ${GO_BUILD_LDFLAGS}" \
      -o "${OUTPUT_BIN}" \
      "${INPUT_CMD}"

FROM scratch

ARG NAME=shaper-webhook
ARG OUTPUT_BIN="/bin/${NAME}"
COPY --from=builder ${OUTPUT_BIN} ${OUTPUT_BIN}
CMD [ "/bin/shaper-webhook" ]
